spring.application.name=SudharshanLogistics

# ===============================
# = Server Configuration
# ===============================
server.port=8080
#server.address=0.0.0.0

# ===============================
# = Database Configuration
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/SudharshanLogistics_Project
#spring.datasource.username=root
#spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

 spring.datasource.url=jdbc:mysql://shrimahalaxmioils.xyz:3306/shrimaha7_sudarshan
 spring.datasource.username=shrimaha7_sudarshan
 spring.datasource.password=code@2025


# ===============================
# = JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=false
spring.main.allow-bean-definition-overriding=true


spring.servlet.multipart.max-file-size=10MB

# ========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# = Logging SQL Bind Parameters (Optional)
# ====================RACE

# = Mail Configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.fallback=support@mycompany.com

# Disable mail health indicator since we use dynamic email config
management.health.mail.enabled=false


#==================================
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000